= GITIGNORE(5)

Git Manual

== Name

* gitignore - Specifies intentionally untracked files to ignore

== Synopsis

$XDG_CONFIG_HOME/git/ignore, $GIT_DIR/info/exclude, .gitignore

== Description

* A *gitignore* file specifies intentionally untracked files that Git should
  ignore.
* Files already tracked by Git are not affected; see the NOTES below for
  details.

'''

* Each line in a *gitignore* file specifies a pattern.
* When deciding whether to ignore a path, Git normally checks *gitignore*
  patterns from multiple sources, with the following order of precedence, from
  highest to lowest (within one level of precedence, the last matching pattern
  decides the outcome):
** Patterns read from the command line for those commands that support them.
** Patterns read from a *.gitignore* file in the same directory as the path, or
   in any parent directory (up to the top-level of the working tree), with
   patterns in the higher level files being overridden by those in lower level
   files down to the directory containing the file. +
   These patterns match relative to the location of the *.gitignore* file. +
   A project normally includes such *.gitignore* files in its repository,
   containing patterns for files generated as part of the project build.
** Patterns read from *$GIT_DIR/info/exclude*.
** Patterns read from the file specified by the configuration variable
   *core.excludesFile*.

* Which file to place a pattern in depends on how the pattern is meant to be
  used.
** Patterns which should be version-controlled and distributed to other
   repositories via clone (i.e., files that all developers will want to ignore)
   should go into a `.gitignore` file.
** Patterns which are specific to a particular repository but which do not need
   to be shared with other related repositories (e.g., auxiliary files that
   live inside the repository but are specific to one user's workflow) should
   go into the *$GIT_DIR/info/exclude* file.
** Patterns which a user wants Git to ignore in all situations (e.g., backup or
   temporary files generated by the user's editor of choice) generally go into
   a file specified by *core.excludesFile* in the user's *~/.gitconfig*. +
   Its default value is $XDG_CONFIG_HOME/git/ignore. +
   If $XDG_CONFIG_HOME is either not set or empty, $HOME/.config/git/ignore is
   used instead.

* The underlying Git plumbing tools, such as [.underline]#git#
  [.underline]#ls-files# and [.underline]#git# [.underline]#read-tree#, read
  *gitignore* patterns specified by command-line options, or from files
  specified by command-line options.
* Higher-level Git tools, such as [.underline]#git# [.underline]#status# and
  [.underline]#git# [.underline]#add#, use patterns from the sources specified
  above.

== Pattern format

* A blank line matches no files, so it can serve as a separator for
  readability.
* A line starting with # serves as a comment. +
  Put a backslash ("\") in front of the first hash for patterns that begin with
  a hash.
* Trailing spaces are ignored unless they are quoted with backslash ("\").
* An optional prefix "!" which negates the pattern; any matching file excluded
  by a previous pattern will become included again. +
  It is not possible to re-include a file if a parent directory of that file is
  excluded. +
  Git doesn't list excluded directories for performance reasons, so any
  patterns on contained files have no effect, no matter where they are
  defined. +
  Put a backslash ("\") in front of the first "!" for patterns that begin with
  a literal "!".
* The slash [.underline]#/# is used as the directory separator. +
  Separators may occur at the beginning, middle or end of the *.gitignore*
  search pattern.
* If there is a separator at the beginning or middle (or both) of the pattern,
  then the pattern is relative to the directory level of the particular
  *.gitignore* file itself. +
  Otherwise the pattern may also match at any level below the *.gitignore*
  level.
* If there is a separator at the end of the pattern then the pattern will only
  match directories, otherwise the pattern can match both files and
  directories.
* For example, a pattern *doc/frotz/* matches *doc/frotz* directory, but not
  *a/doc/frotz* directory; however *frotz/* matches *frotz* and *a/frotz* that
  is a directory (all paths are relative from the *.gitignore* file).
* An asterisk "*" matches anything except a slash. +
  The character "?" matches any one character except "/". +
  The range notation, e.g. *[a-zA-Z]*, can be used to match one of the
  characters in a range. +
  See fnmatch(3) and the FNM_PATHNAME flag for a more detailed description.

== GIT

* Part of the *git*(1) suite

[%autowidth]
|===
|Git 2.48.1	|02/17/2025
|===
