= PAM-AUTH-UPDATE(8)

* System Manager's Manual

== Name

* pam-auth-update - manage PAM configuration using packaged profiles

== Synopsis

[subs="attributes,quotes+"]
....
*pam-auth-update* {startsb}**--package** {startsb}**--remove**
	[.underline]#profile# {startsb}[.underline]##profile##...]]]
	[*--force*] {startsb}**--enable** [.underline]#profile#
	{startsb}[.underline]##profile##...]]  {startsb}**--disable**
	[.underline]#profile# {startsb}[.underline]##profile##...]]
....

== Description

* [.underline]#pam-auth-update# is a utility that permits configuring the
  central authentication policy for the system using pre-defined profiles as
  supplied by PAM module packages.
* Profiles shipped in the [.underline]#/usr/share/pam-configs/# directory
  specify the modules, with options, to enable; the preferred ordering with
  respect to other profiles; and whether a profile should be enabled by default.
* Packages providing PAM modules register their profiles at install time by
  calling *pam-auth-update --package*.
* Selection of profiles is done using the standard debconf interface.
* The profile selection question will be asked at 'medium' priority when
  packages are added or removed, so no user interaction is required by
  default.
* Users may invoke *pam-auth-update* directly to change their authentication
  configuration.

'''

* The script makes every effort to respect local changes to
  [.underline]#/etc/pam.d/common-*#.
* Local modifications to the list of module options will be preserved, and
  additions of modules within the managed portion of the stack will cause
  *pam-auth-update* to treat the config files as locally modified and not make
  further changes to the config files unless given the *--force* option.

'''

* If the user specifies that *pam-auth-update* should override local
  configuration changes, the locally-modified files will be saved in
  [.underline]#/etc/pam.d/# with a suffix of [.unerline]#.pam-old#.

'''

* Debian 08/23/2008
