= PDFTK(1)
:toc: left

* General Commands Manual

== Name

* pdftk - A handy tool for manipulating PDF

== Synopsis

[subs=quotes]
....
*pdftk* [.underline]#&lt;input PDF files | - | PROMPT>#
     [ *input_pw* [.underline]#&lt;input PDF owner passwords | PROMPT># ]
     [ [.underline]#&lt;operation># [.underline]#&lt;operation arguments># ]
     [ *output* [.underline]#&lt;output filename | - | PROMPT># ]
Where:
     [.underline]#&lt;operation># may be empty, or:
     [ *cat* | *burst* ]
....

* For Complete Help: *pdftk --help*

== Description

* If PDF is electronic paper, then pdftk is an electronic staple-remover,
  hole-punch, binder, secret-decoder-ring, and X-Ray-glasses.
* Pdftk is a simple tool for doing everyday things with PDF documents.
* Use it to:
** Merge PDF Documents or Collate PDF Page Scans
** Split PDF Pages into a New Document
** Rotate PDF Documents or Pages
** Decrypt Input as Necessary (Password Required)

== Options

* A summary of options is included below.

'''

--help, -h::
* Show this summary of options.

<input PDF files | - | PROMPT>::
* A list of the input PDF files.
* If you plan to combine these PDFs (without using handles) then list files in
  the order you want them combined.
* Use - to pass a single PDF into pdftk via stdin.
* Input files can be associated with handles, where a handle is one or more
  upper-case letters:
+
[subs=quotes]
....
[.underline]#&lt;input PDF handle>#=[.underline]#&lt;input PDF filename>#
....

* Handles are often omitted.
* They are useful when specifying PDF passwords or page ranges, later.
+
'''

* For example: A=input1.pdf QT=input2.pdf M=input3.pdf

[input_pw <input PDF owner passwords | PROMPT>]::
* Input PDF owner passwords, if necessary, are associated with files by using their handles:
+
[subs=quotes]
....
[.underline]#&lt;input PDF handle>#=[.underline]#&lt;input PDF file owner password>#
....

* If handles are not given, then passwords are associated with input files by
  order.
+
'''
* Most pdftk features require that encrypted input PDF are accompanied by the
  \~owner~ password.
* If the input PDF has no owner password, then the user password must be given,
  instead.
* If the input PDF has no passwords, then no password should be given.
+
'''

* When running in *do_ask* mode, pdftk will prompt you for a password if the
  supplied password is incorrect or none was given.

[<operation> <operation arguments>]::
* If this optional argument is omitted, then pdftk runs in 'filter' mode.
* Filter mode takes only one PDF input and creates a new PDF after applying all
  of the output options, like encryption and compression.

cat [<page ranges>]:::
** Assembles (catenates) pages from input PDFs to create a new PDF.
** Use cat to merge PDF pages or to split PDF pages from documents.
** You can also use it to rotate PDF pages.
** Page order in the new PDF is specified by the order of the given page ranges.
** Page ranges are described like this:
+
[subs=quotes]
....
[.underline]#&lt;input PDF handle>#[[.underline]#&lt;begin page number>#[-[.underline]#&lt;end page number>#[[.underline]#&lt;qualifier>#]]][[.underline]#&lt;page rotation>#]
....

** Where the handle identifies one of the input PDF files, and the beginning and
   ending page numbers are one-based references to pages in the PDF file.
** The qualifier can be *even*, *odd*, or *~*, and the page rotation can be
   *north*, *south*, *east*, *west*, *left*, *right*, or *down*.
+
'''

** If a PDF handle is given but no pages are specified, then the entire PDF is
   used.
** If no pages are specified for any of the input PDFs, then the input PDFs'
   bookmarks are also merged and included in the output.
+
'''

** If the handle is omitted from the page range, then the pages are taken from
   the first input PDF.

'''

** The *even* qualifier causes pdftk to use only the even-numbered PDF pages, so
   *1-6even* yields pages 2, 4 and 6 in that order.
** *6-1even* yields pages 6, 4 and 2 in that order.
+
'''

** The *odd* qualifier works similarly to the *even*.
+
'''

** Pages can be subtracted from a page range using the *~* qualifier followed by
   a page range.
** For instance, *1-20~5-6* and *1-20\~5~6* are equivalent to 1-4 7-20, and *~5*
   yields all pages except page 5.
** Depending on your shell, you may need to quote this argument because of the ~
   at the beginning.
+
'''

** The page rotation setting can cause pdftk to rotate pages and documents.
** Each option sets the page rotation as follows (in degrees): *north*: 0,
   *east*: 90, *south*: 180, *west*: 270, *left*: -90, *right*: +90, *down*:
   +180.
** *left*, *right*, and *down* make relative adjustments to a page's rotation.
+
'''

** If no arguments are passed to cat, then pdftk combines all input PDFs in the
   order they were given to create the output.
+
'''
+
[NOTE]
====
* [.underline]#&lt;end page number># may be less than [.underlin]#&lt;begin page
  number>#.
* The keyword *end* may be used to reference the final page of a document
  instead of a page number.
* Reference a single page by omitting the ending page number.
* The handle may be used alone to represent the entire PDF document, e.g.,
  B1-end is the same as B.
* You can reference page numbers in reverse order by prefixing them with the
  letter *r*. +
  For example, page r1 is the last page of the document, r2 is the next-to-last
  page of the document, and rend is the first page of the document. +
  You can use this prefix in ranges, too, for example r3-r1 is the last three
  pages of a PDF.
====

burst:::
** Splits a single input PDF document into individual pages.
** Also creates a report named doc_data.txt which is the same as the output from
   *dump_data*.
** The *output* section can contain a printf-styled format string to name these
   pages.
+
'''

** For example, if you want pages named page_01.pdf, page_02.pdf, etc., pass
   *output page_%02d.pdf* to pdftk.
** If the pattern is omitted, then a default pattern pg_%04d.pdf is appended and
   produces pages named pg_0001.pdf, pg_0002.pdf, etc.

== Examples

* The following examples use actual passwords as command line parameters, which
  is discouraged (see the Security considerations section).

.Decrypt a PDF
....
pdftk secured.pdf input_pw foopass output unsecured.pdf
....

.Join two files, one of which requires the password 'foopass'. The output is not encrypted.
....
pdftk A=secured.pdf 2.pdf input_pw A=foopass cat output 3.pdf
....

.Join in1.pdf and in2.pdf into a new PDF, out1.pdf
....
pdftk in1.pdf in2.pdf cat output out1.pdf
....

* or (using handles):
+
....
pdftk A=in1.pdf B=in2.pdf cat A B output out1.pdf
....

* or (using wildcards):
....
pdftk *.pdf cat output combined.pdf
....

.Remove page 13 from in1.pdf to create out1.pdf
....
pdftk in.pdf cat 1-12 14-end output out1.pdf
....

* or:
+
....
pdftk A=in1.pdf cat A1-12 A14-end output out1.pdf
....

.Burst a single PDF document into pages and dump its data to doc_data.txt
....
pdftk in.pdf burst
....

.Rotate the first PDF page to 90 degrees clockwise
....
pdftk in.pdf cat 1east 2-end output out.pdf
....

.Rotate an entire PDF document to 180 degrees
....
pdftk in.pdf cat 1-endsouth output out.pdf
....

== Security considerations

* Passing a password as a command line parameter is insecure because it can get
  saved into the shell's history and be accessible by other users via /proc.
* Use the keyword *PROMPT* and input any passwords via standard input instead.

'''

* December 7, 2020
