= utmp(5)

* File Formats Manual

== Name

* utmp, wtmp - login records

== Synopsis

[source,c]
#include <utmp.h>

== Description

* The [.underline]#utmp# file allows one to discover information about who is
  currently using the system.
* There may be more users currently using the system, because not all programs
  use utmp logging.

[WARNING]
====
* [.underline]#utmp# must not be writable by the user class "other", because
  many system programs (foolishly) depend on its integrity.
* You risk faked system logfiles and modifications of system files if you
  leave [.underline]#utmp# writable to any user other than the owner and group
  owner of the file.
====

* The file is a sequence of [.underline]#utmp# structures, declared as follows
  in [.underline]#<utmp.h># (note that this is only one of several definitions
  around; details depend on the version of libc):

[,c]
----
/* Values for ut_type field, below */

...
#define BOOT_TIME     2 /* Time of system boot (in ut_tv) */
...
#define UT_NAMESIZE      32
#define UT_HOSTSIZE     256

...

struct utmp {
	...
	char	[UT_NAMESIZE];		/* Username */
	char	ut_host[UT_HOSTSIZE];	/* Hostname for remote login, or
					   kernel version for run-level
					   messages */
	...
	/* The ut_session and ut_tv fields must be the same size when
	   compiled 32- and 64-bit.  This allows data files and shared
	   memory to be shared between 32- and 64-bit applications. */
#if __WORDSIZE == 64 && defined __WORDSIZE_COMPAT32
	int32_t	ut_session;		/* Session ID (getsid(2)),
					   used for windowing */
	struct {
		int32_t tv_sec;		/* Seconds */
		int32_t tv_usec;	/* Microseconds */
	} ut_tv;			/* Time entry was made */
#else
	long   ut_session;		/* Session ID */
	struct timeval ut_tv;		/* Time entry was made */
#endif
};
----

'''

* Linux man-pages 6.03, 2023-02-05
